version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "${SERVER_PORT}:3000"
    env_file:
      - .env
    environment:
      PGRST_DB_URI: postgres://${USERNAME}:${PASSWORD}@${DB_URI}
      PGRST_DB_SCHEMA: ${DB_SCHEMA}
      PGRST_DB_ANON_ROLE: ${USERNAME} #In production this role should not be the same as the one used for the connection
      PGRST_OPENAPI_SERVER_PROXY_URI: ${OPENAPI_URI}

